# Generated by Django 5.2.5 on 2025-11-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0002_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confessions', to='confessions.community'),
        ),
    ]
