# Generated by Django 5.2.5 on 2025-11-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0003_confession_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
